name: FitForge
options:
  bundleIdPrefix: fitforge.stone
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
settings:
  base:
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    CODE_SIGN_STYLE: Automatic
targets:
  FitForge:
    type: application
    platform: iOS
    sources:
      - path: Sources
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: FitForge
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIAppFonts:
          - Cinzel-400.ttf
          - Cinzel-600.ttf
          - Cinzel-700.ttf
          - Inter-300.ttf
          - Inter-400.ttf
          - Inter-500.ttf
          - Inter-600.ttf
          - Inter-700.ttf
          - DMMono-300.ttf
          - DMMono-400.ttf
          - DMMono-500.ttf
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: fitforge.stone.app
        PRODUCT_NAME: FitForge
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
